# render.yaml

services:
  # 🛠️ Django Backend Service
  - type: web
    name: portfolio-backend
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn AuthAPI.wsgi:application
    envVars:
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY
      - key: CREATE_SUPERUSER
        value: "True"
      - key: DJANGO_SUPERUSER_EMAIL
        fromEnvVar: DJANGO_SUPERUSER_EMAIL
      - key: DJANGO_SUPERUSER_PASSWORD
        fromEnvVar: DJANGO_SUPERUSER_PASSWORD

  # 🌐 Next.js Frontend Service
  - type: static
    name: portfolio-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_MODE
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        fromEnvVar: NEXT_PUBLIC_API_BASE_URL


